test:
  _target_: src.datasets.CustomTextDirDataset
  target_sr: 22050
  audio_length_limit: null
  text_as_input: True
  transcription_dir: /home/teasgen/dla/neural_vocoder/test_data_text
  instance_transforms: ${transforms.instance_transforms.train}
