test:
  _target_: src.datasets.CustomSingleTextDataset
  target_sr: 22050
  audio_length_limit: null
  text_as_input: True
  transcription: "Bla bla bla"
  instance_transforms: ${transforms.instance_transforms.inference}
