defaults:
  - model: hifigan
  - writer: wandb
  - metrics: dummy_vocoder
  - datasets: ljspeech
  - dataloader: example
  - transforms: example_only_instance
  - _self_

D_optimizer:
  _target_: torch.optim.AdamW
  weight_decay: 1e-2
  lr: 2e-5
D_lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 3e-5
  pct_start: 0.03
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

G_optimizer:
  _target_: torch.optim.AdamW
  weight_decay: 1e-2
  lr: 3e-5
G_lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 3e-5
  pct_start: 0.0
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos


D_loss_function:
  _target_: src.loss.HiFiGANLossDiscriminator

G_loss_function:
  _target_: src.loss.HiFiGANLossGenerator

trainer:
  log_step: 50
  n_epochs: 200
  epoch_len: 175
  G_max_grad_norm: 10
  D_max_grad_norm: 10
  device_tensors: ["wav", "mel_spectrogram"]
  resume_from: null
  device: auto
  override: True
  monitor: "min test_L1MelMetric"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 42
